### ISSUE TITLE
注释isHostCorrect

### ISSUE THREAD

**Issue by alley-vill** [cklwblove/vue-cli-plugin-qrcode#4]
![image](https://user-images.githubusercontent.com/22758452/70694239-1486c600-1cfa-11ea-845f-1b07aad14cdd.png)
// const isHostCorrect =
                //   options.devServer.host.trim() === '0.0.0.0';

                // if (!isHostCorrect) {
                //   showHostWarning();
                //   callback && callback();
                //   return;
                // }

我注释了这段ok了

**Comment by cklwblove** [comment]
感谢反馈，也可以在 `vue.config.js`  -> `devServer `-> `host `设置成 **'0.0.0.0'**
